### PR TITLE
Fix ie11 memory leak

### PR DESCRIPTION
**Pull request by adm90**
When IE 11 converts it to ZIP, it seems that it has not been released since it consumes a lot of memory.
This pull request implementing memory release.

- Test file total size is 12.6 MB
- Before: first, 92MB to 1.7GB,  and not release memory.
before

- After:  fixed, There is no problem even if repeating.
after

If necessary, I will show sample code as well.

### CODE REVIEW

**Comment by Shammah** [comment]
I too had a memory leak problem with only IE11; when zipping a 12.6MB file my browser would allocate more than 1.3GB of memory, and the browser would hang. This was not the case in Edge and Chrome. After applying this patch, the memory leak was gone in IE11 and the browser could successfully zip.

**Comment by dduponchel** [comment]
I think it comes from #357 (released in v3.1.3). I will check if the version 3.1.2 has the same issue.

**Comment by adm90** [comment]
I confirmed it. As you said, there was no problem with version 3.1.2.

**Comment by dduponchel** [comment]
I reproduced the issue on IE 11 and Edge. I found the issue on Microsoft bug tracker: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7115840/

I find your fix is a bit too broad: `MSBlobBuilder` exists in both browsers, so I hesitate between your solution and a revert of #357:
- in one case IE/Edge uses 2 times the memory needed by other browsers (which won't be a pleasant surprise), even if/when Edge fix the issue
- in the other case everyone takes more memory **but** the behavior is more uniform

**Comment by dduponchel** [comment]
I'll take the revert of #357, I'll update this pull request to change the behavior.

**Pull request merged**
