### PR TITLE
fixed 'End of data reached' error when file extra field is invalid

### PR DESCRIPTION
**Pull request by mljsgto222**
fixed for #543

### CODE REVIEW

**Comment by AndreevskiAleksandar** [comment]
When will this be merged? I am experiencing the same issues with epub files..

**Comment by eschultz** [comment]
This PR fixed issues I was having extracting some APK files.  Please merge!

**Comment by eschultz** [comment]
PING @Stuk

**Comment by lednax** [comment]
PING @Stuk

**Comment by Stuk** [comment]
I'm afraid I'm very low on spare time at the moment, and unfortunately this PR doesn't have any tests to guarantee it won't break again in the future. @eschultz, @lednax or @mljsgto222 would you be able to recreate this PR with a test? I can merge it then

**Comment by mljsgto222** [comment]
@Stuk , I have added test for this PR

**Comment by Stuk** [comment]
Thanks!

**Pull request merged**
