### PR TITLE
Fix equality checks

### PR DESCRIPTION
**Pull request by evilaliv3**
I've fixed few equalities tests and while retesting it added few testing refinements.

### CODE REVIEW

**Comment by dduponchel** [comment]
I thought `eqeqeq` was turned on by default on jshint... Good catch !
Triggering the saucelabs tests only once is cool, but your `env` doesn't seem to work as expected: [this is translated](https://travis-ci.org/Stuk/jszip/jobs/118064295#L133) as `export env=COMMAND=test-node`, `npm run $COMMAND` is the same as `npm run` and prints the help.

**Comment by evilaliv3** [comment]
not everything turns out as it should!

give me a second try!

**Comment by evilaliv3** [comment]
yep i forgot the syntax of this that is the same we use on openpgp.js/globaleaks: https://github.com/openpgpjs/openpgpjs/blob/master/.travis.yml

**Comment by dduponchel** [comment]
Nice !

**Comment by evilaliv3** [comment]
:)

**Pull request merged**
