### PR TITLE
Improve better performance

### PR DESCRIPTION
**Pull request by xqdoo00o**
Use larger chunkSize(64K) increase generateasync perf。
And use a [robust setimmediate polyfill](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) could increase generateasync perf of the zip with lots of chunks (min.js just 1KB larger ).
(Current setImmediate polyfill (after v3.15) using setTimeout(fn, 0) cause 4ms+ delay(browser) or 1ms delay(node.js) each chunk (current 16K size), see [perf demo](http://jphpsf.github.io/setImmediate-shim-demo/)).

> Test result for a zip with 16 files(chunks):
> before:
>   store: 200ms
> after:
>   store: 30ms

This PR may resolve the issue #617.

### CODE REVIEW

**Comment by 101arrowz** [comment]
@Stuk updates on this? There's a massive difference in performance between [3.1.5](https://codesandbox.io/s/friendly-sun-t561i) and [3.5.0](https://codesandbox.io/s/peaceful-sid-vu6sl).

**Comment by fpaupier** [comment]
Still having this issue with the proposed workaround. Any tips?

**Comment by 101arrowz** [comment]
I'd recommend switching to a different library, at least until this is merged. [zip.js](https://github.com/gildas-lormeau/zip.js) and [fflate](https://github.com/101arrowz/fflate) (my own library) are solid alternatives.

**Comment by mark-westerhof** [comment]
Can this merge now?

**Comment by AlttiRi** [comment]
What do you waiting for?

[set-immediate-shim](https://www.npmjs.com/package/set-immediate-shim) is [**unacceptably slow**](https://github.com/Stuk/jszip/issues/617).
The existence of this lib is a joke, [it only provides `setTimeout` with "setImmediate" name.](https://github.com/sindresorhus/set-immediate-shim/blob/main/index.js) _The absolutely useless "library"._ 

Or [setimmediate](https://www.npmjs.com/package/setimmediate) is too big for you?

---

Since `delay` uses only the callback param of `setImmediate`

https://github.com/Stuk/jszip/blob/38f837313ee94bbef2328c47e0f48fd43ceb3300/lib/utils.js#L404-L408

...just use the follow code instead of importing a library:

```js
const setImmediate = globalThis.setImmediate || /*#__PURE__*/ (function() {
    const {port1, port2} = new MessageChannel();
    const queue = [];
    port1.onmessage = function() {
        const callback = queue.shift();
        callback();
    };
    return function setImmediateLike(callback) { // Simplified implementation: only callback argument.
        port2.postMessage(null);
        queue.push(callback);
    };
})();
```

The implementation of `setImmediate` based on `MessageChannel` is supported everywhere:
https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel#browser_compatibility
https://caniuse.com/mdn-api_messagechannel_messagechannel


---

ES5 version to pass linter:
```js
var setImmediate = typeof setImmediate === "function" ? setImmediate : /*#__PURE__*/ (function() {
    var channel = new MessageChannel();
    var port1 = channel.port1;
    var port2 = channel.port2;
    var queue = [];
    port1.onmessage = function() {
        var callback = queue.shift();
        callback();
    };
    return function setImmediateLike(callback) { // Simplified implementation: only callback argument.
        port2.postMessage(null);
        queue.push(callback);
    };
})();
```

Just put it before 404 line _(also remove the import and the dependency):_
https://github.com/Stuk/jszip/blob/38f837313ee94bbef2328c47e0f48fd43ceb3300/lib/utils.js#L404

All tests are passed. Works properly. And fast (as expected).
```
# pass 186
...
chromium { passed: 3301, failed: 0, total: 3301, runtime: 8940, tests: [] }
firefox { passed: 3301, failed: 0, total: 3301, runtime: 8585, tests: [] }
webkit { passed: 3301, failed: 0, total: 3301, runtime: 8367, tests: [] }
```

**Pull request closed without merging**
