### PR TITLE
Dependency updates.

### PR DESCRIPTION
**Pull request by coreyfarrell**
* Replace core-js with the much smaller set-immediate-shim.
* Remove es6-promise as it is unused.
* Update lie and readable-stream.

The change from core-js to set-immediate-shim reduces the install size
of jszip from 9.1MB to 2.2MB.  The ponyfil for setImmediate is all that
was used from core-js.

### CODE REVIEW

**Comment by chuyik** [comment]
Sorry to ping @Stuk could this PR be reviewed?

**Comment by chuyik** [comment]
For anyone interested, I've forked this PR into a new package `@chuyik/jszip`, and all tests [passed](https://travis-ci.org/chuyik/jszip).

npm: https://www.npmjs.com/package/@chuyik/jszip
github: https://github.com/chuyik/jszip

**Comment by coreyfarrell** [comment]
@chuyik the tests passed here (CI is enabled).  Unfortunately for me a scoped fork cannot help me as `jszip` is an indirect dependency via selenium-webdriver.

**Comment by Stuk** [comment]
I'll publish this as version 3.2.0 in the morning PST.

Unfortunately there's been some bitrot and the Saucelabs configurations are out of date, meaning I can't confirm that this works across all browsers. Looking at the change I think it should be ok.

**Comment by coreyfarrell** [comment]
@Stuk thanks, maybe #506 could be included as well?

**Comment by Stuk** [comment]
Done and done!

**Comment by jimmywarting** [comment]
Grate to see @Stuk working on jszip again 👍😃 
welcome back

**Comment by PrzemyslawKlys** [comment]
image

Those files, downloaded from newest release 3.2.0 seem to contain

image

Are those updated or a mistake?

**Comment by Stuk** [comment]
Thanks for catching. I've published 3.2.1 with the correct dist files

**Pull request merged**
