### PR TITLE
JSZIP:Removed PhantomJS Dependency

### PR DESCRIPTION
**Pull request by ossdev07**
Phantomjs is an unmaintained project, removed phantomjs dependency from package.json by updating grunt-contrib-qunit version to 3.0.1 and by removing phantomjs prebuilt from devdependency.

Updated nodejs version in the travis.yml file as the earlier version used was very old.

Signed-off-by: ossdev <ossdev@puresoftware.com>

### CODE REVIEW

**Comment by jimmywarting** [comment]
could as well remove v6 as End-of-life support is just 15 days away

https://github.com/nodejs/Release

**Comment by ossdev07** [comment]
Hi @jimmywarting 

If you agree then I can remove the version 6 as well from the pull request.
Also Please could you have a look at this PR and suggest what it would take to merge this.

**Comment by jimmywarting** [comment]
Fine by me, but perhaps not up to me to decide.

@dduponchel and @Stuk have been off grid for a bit regarding this package.

**Comment by Stuk** [comment]
Thanks for the PR! I have updated these deps in https://github.com/Stuk/jszip/pull/605

**Comment by ossdev07** [comment]
@Stuk Thanks for the Update.

But you have not removed the phantomjs dependency from the package.json, phantomjs is unmaintained project and it will be a delight to see phantomjs removed from the package.

**Comment by Stuk** [comment]
Ah, you're right. Now _actually_ removed in 8742db3a5f725f6651948018d77be3499059814d

**Pull request closed without merging**
